# Generated by Django 5.0.3 on 2024-06-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_comment='uuid', max_length=300)),
                ('name', models.CharField(db_comment='用户名', max_length=300)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_comment='创建时间', null=True)),
            ],
            options={
                'db_table': 'app_user',
                'db_table_comment': '用户表',
                'indexes': [models.Index(fields=['uuid'], name='app_user_uuid_5b1ff8_idx')],
            },
        ),
    ]
